-- Manual SQL script to apply the run_id migration
-- Run this in the Supabase Dashboard > SQL Editor

-- Migration 008: Update runs table primary key to UUID with auto-generation
-- This allows Supabase to auto-generate the internal Run ID

-- First, add a new UUID column with auto-generation
ALTER TABLE runs 
ADD COLUMN run_id UUID DEFAULT gen_random_uuid();

-- Update existing records to have a UUID
UPDATE runs SET run_id = gen_random_uuid() WHERE run_id IS NULL;

-- Make the new column NOT NULL
ALTER TABLE runs ALTER COLUMN run_id SET NOT NULL;

-- Create a unique index on the new column
CREATE UNIQUE INDEX idx_runs_run_id ON runs(run_id);

-- Add comment for documentation
COMMENT ON COLUMN runs.run_id IS 'Internal Run ID (UUID) - auto-generated by Supabase';

-- Note: We'll keep the old 'id' column for now to avoid breaking existing references
-- The old 'id' column will eventually be removed in a future migration
-- For now, it will contain the Apify run ID or temporary values
