-- Migration 009: Simplify ID structure - use only 2 IDs
-- Change id column to UUID and remove run_id column

-- First, create a backup of existing data
CREATE TABLE runs_backup AS SELECT * FROM runs;
CREATE TABLE files_backup AS SELECT * FROM files;

-- Drop foreign key constraints that depend on runs_pkey
ALTER TABLE files DROP CONSTRAINT IF EXISTS files_run_id_fkey;

-- For now, let's keep the files table as-is and just update the runs table
-- We'll handle the files table in a separate migration if needed

-- Drop the old id column (which is TEXT)
ALTER TABLE runs DROP CONSTRAINT runs_pkey;
ALTER TABLE runs DROP COLUMN id;

-- Add new id column as UUID with auto-generation
ALTER TABLE runs 
ADD COLUMN id UUID DEFAULT gen_random_uuid() PRIMARY KEY;

-- Update existing records to have UUIDs
UPDATE runs SET id = gen_random_uuid() WHERE id IS NULL;

-- Make the new column NOT NULL
ALTER TABLE runs ALTER COLUMN id SET NOT NULL;

-- Drop the run_id column (no longer needed)
ALTER TABLE runs DROP COLUMN run_id;

-- Drop the unique index on run_id (no longer exists)
DROP INDEX IF EXISTS idx_runs_run_id;

-- For now, we'll leave the files table with TEXT run_id
-- This will be handled in a separate migration to avoid data loss
-- The foreign key constraint will be re-added later

-- Add comment for documentation
COMMENT ON COLUMN runs.id IS 'Primary key (UUID) - auto-generated by Supabase';
COMMENT ON COLUMN runs.apify_run_id IS 'Apify run ID - set after actor starts';

-- Verify the structure
-- Now we have: 
-- runs: id (UUID PRIMARY KEY), apify_run_id (TEXT), code, code_type, etc.
-- files: id (UUID PRIMARY KEY), run_id (TEXT) - will be updated in next migration
